# aifriend-go/config.yaml
server:
  port: ":8000"
  # dev prod
  mode: "dev"
  allow_register: true
  # 全局服务开关
  enable: true

db:
  mysql_dsn:
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 3600 # 秒
  # 重试次数
  connect_max_retries: 20
  # 重试等待时间(秒)
  connect_retry_interval: 3

jwt:
  # 测试密钥
  access_secret:
  refresh_secret:
  rotate_refresh_tokens: true
  blacklist_after_rotation: true

# Prometheus 监控配置
prometheus:
  enable: true
  http_addr: "127.0.0.1:8001"

llm:
  # .env 文件配置
  api_key:
  api_base:
  model_name: "deepseek-v3.2"